name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "Connected"

            cd /root/Starbucks-Application

            git fetch origin
            git reset --hard origin/main

            docker stop starbucks-app || true
            docker rm starbucks-app || true

            docker build -t starbucks-app .

            docker run -d \
              --name starbucks-app \
              -p 80:3000 \
              --restart always \
              starbucks-app

            docker ps
