name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐳 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "✅ Connected"

            cd /root/Starbucks-Application

            echo "📥 Updating code"
            git fetch origin
            git reset --hard origin/main

            echo "🧹 Remove old container"
            docker stop Starbucks-Application || true
            docker rm Starbucks-Application || true

            echo "🧹 Remove old image"
            docker rmi Starbucks-Application || true

            echo "🏗 Build image"
            docker build -t Starbucks-Application .

            echo "🚀 Start container"
            docker run -d \
              --name Starbucks-Application \
              -p 80:3000 \
              --restart always \
              Starbucks-Application

            echo "📋 Running containers"
            docker ps
