name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐳 Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Connected to EC2"

            # Go to project folder
            cd /home/ubuntu/Starbucks-Application

            # Pull latest code
            git pull origin main
            echo "✅ Code pulled"

            # Stop old container if running
            docker stop Starbucks-Application || true
            docker rm Starbucks-Application || true
            echo "✅ Old container removed"

            # Build new Docker image
            docker build -t Starbucks-Application .
            echo "✅ New image built"

            # Run new container
            docker run -d \
              --name Starbucks-Application \
              -p 80:80 \
              --restart always \
              Starbucks-Application
            echo "🚀 New container is live!"
